spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/docker_k8s_demo?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_CONNECTION_USERNAME:root}
    password: ${DB_CONNECTION_PASSWORD:password}
  jpa:
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
